export default [
  {
    "_id": "Q101",
    "title": "Propulsion Fundamentals Quiz",
    "course": "RS101",
    "description": "Test your knowledge of rocket propulsion basics.",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": false,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 10 at 11:59pm",
    "availableDate": "May 3 at 12:00am",
    "untilDate": "May 10 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q102",
    "title": "Combustion Processes Quiz",
    "course": "RS101",
    "description": "Quiz on combustion analysis and efficiency.",
    "quizType": "Graded Quiz",
    "points": 40,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 15,
    "multipleAttempts": true,
    "showCorrectAnswers": "After due date",
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 17 at 11:59pm",
    "availableDate": "May 10 at 12:00am",
    "untilDate": "May 17 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q103",
    "title": "Nozzle Design Quiz",
    "course": "RS101",
    "description": "Assessment on nozzle design principles.",
    "quizType": "Graded Quiz",
    "points": 45,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 25,
    "multipleAttempts": false,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": true,
    "dueDate": "May 24 at 11:59pm",
    "availableDate": "May 17 at 12:00am",
    "untilDate": "May 24 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q201",
    "title": "Aerodynamics Basics Quiz",
    "course": "RS102",
    "description": "Foundational concepts in aerodynamics.",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": true,
    "showCorrectAnswers": "After last attempt",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 10 at 11:59pm",
    "availableDate": "May 3 at 12:00am",
    "untilDate": "May 10 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q202",
    "title": "Flow Dynamics Quiz",
    "course": "RS102",
    "description": "Quiz on fluid flow and dynamics.",
    "quizType": "Graded Quiz",
    "points": 45,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": false,
    "timeLimit": 30,
    "multipleAttempts": false,
    "showCorrectAnswers": "Immediately",
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 17 at 11:59pm",
    "availableDate": "May 10 at 12:00am",
    "untilDate": "May 17 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q203",
    "title": "Subsonic vs Supersonic Quiz",
    "course": "RS102",
    "description": "Test on subsonic and supersonic flow.",
    "quizType": "Graded Quiz",
    "points": 40,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": true,
    "showCorrectAnswers": "After due date",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 24 at 11:59pm",
    "availableDate": "May 17 at 12:00am",
    "untilDate": "May 24 at 11:59pm",
    "published": false
  },
  {
    "_id": "Q301",
    "title": "Spacecraft Structures Quiz",
    "course": "RS103",
    "description": "Quiz covering spacecraft structural design.",
    "quizType": "Graded Quiz",
    "points": 50,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 25,
    "multipleAttempts": false,
    "showCorrectAnswers": "Immediately",
    "accessCode": "SPACE2024",
    "oneQuestionAtATime": true,
    "webcamRequired": true,
    "lockQuestionsAfterAnswering": true,
    "dueDate": "May 10 at 11:59pm",
    "availableDate": "May 3 at 12:00am",
    "untilDate": "May 10 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q302",
    "title": "Materials Engineering Quiz",
    "course": "RS103",
    "description": "Assessment on aerospace materials.",
    "quizType": "Graded Quiz",
    "points": 45,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": true,
    "showCorrectAnswers": "After last attempt",
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 17 at 11:59pm",
    "availableDate": "May 10 at 12:00am",
    "untilDate": "May 17 at 11:59pm",
    "published": true
  },
  {
    "_id": "Q303",
    "title": "Thermal Protection Quiz",
    "course": "RS103",
    "description": "Quiz on thermal protection systems.",
    "quizType": "Graded Quiz",
    "points": 40,
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 15,
    "multipleAttempts": false,
    "showCorrectAnswers": "After due date",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "May 24 at 11:59pm",
    "availableDate": "May 17 at 12:00am",
    "untilDate": "May 24 at 11:59pm",
    "published": true
  }
];
